Fix python3 import error (#249)
```
 File "/home/ryuichi/Dropbox/sp/merlin_pr/src/utils/file_paths.py",
 line 22, in <module>
     from utils import prepare_file_path_list
     ImportError: cannot import name 'prepare_file_path_list'
```

This is because there are two `utils` modules in merlin, src/utils
and src/utils/utils. Fixing this by explicitly importing the module
we need.